name: orpheo_app
description: Aplicación para gestión de miembros y organización masónica.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Updated to enforce null safety

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # Estado y arquitectura
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  dartz: ^0.10.1

  # Navegación
  go_router: ^12.1.1

  # UI
  google_fonts: ^5.1.0
  flutter_spinkit: ^5.2.0

  # Herramientas
  intl: ^0.19.0
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.0.15
  file_picker: ^6.1.1  # Updated version
  image_picker: ^1.0.7
  url_launcher: ^6.1.14

  # Otros
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/